### ISSUE TITLE
Code coverage badge not updating properly

### ISSUE THREAD

**Issue by CMRiggs** [spark1217/slash-group32#3]
Right now the code coverage badge on the ReadMe shows a percentage of 81% while the actual coverage should be somewhere near 53%. I believe this is because the code coverage URL links to the original repository, not our copied one. This is because the latest commit that the CodeCov has stored is shown as being this one https://github.com/vishnuchalla/slash/commit/7b6581d85313983c5d7b9ffcdd81bad761511514 .

**Comment by spark1217** [comment]
This can't be fixable till the code coverage workflow is fixed. Our own link has not been generated since the report hasn't been uploaded.

**Comment by spark1217** [comment]
Updated
